import numpy as np
import pandas as pd
from scipy.integrate import simps

# -------------------- 1. Physical Constants and Simulation Parameters --------------------

# Convert LAMMPS units ('metal' units) to SI for final kappa result (W/m-K)
# LAMMPS 'metal' units: Energy=eV, Distance=Angstrom, Time=ps
EV_TO_J = 1.602176634e-19       # eV to J
A_TO_M = 1.0e-10               # Angstrom to m
PS_TO_S = 1.0e-12              # picosecond to second
KB = 1.380649e-23              # Boltzmann constant (J/K)

# Simulation parameters (MUST match the LAMMPS input file)
T = 300.0                      # Simulation Temperature (K)
V = 10.0*3 * A_TO_M*3        # Simulation Volume (10x10x10 Angstrom^3 converted to m^3)
dt_corr = 0.1 * PS_TO_S        # Time step for correlation data (100 * 0.001 ps converted to s)

# Green-Kubo Formula Constant (SI Units):
# kappa = (1 / 3 V k_B^2 T^2) * Integral_0^inf (<J(t).J(0)> dt)
GK_FACTOR = (1.0 / (3.0 * V * KB*2 * T*2))

# -------------------- 2. Load and Process Data --------------------

# Load the HFACF data file generated by LAMMPS
# The file 'hfacf.dat' contains columns: Step, Time, JxJx, JyJy, JzJz, AvgJx, AvgJy, AvgJz
try:
    # Skip header lines (usually 2, 3, or 4 depending on LAMMPS version)
    df = pd.read_csv('hfacf.dat', sep='\s+', skiprows=4, header=None)
except FileNotFoundError:
    print("Error: 'hfacf.dat' not found. Ensure the LAMMPS script ran successfully.")
    exit()

# Extract the autocorrelation data (columns 3, 4, 5 are JxJx, JyJy, JzJz in hfacf.dat)
# The data is already time-averaged over different origins (t0).
# HFACF_J_dot_J = <Jx(t)Jx(0)> + <Jy(t)Jy(0)> + <Jz(t)Jz(0)>
JxJx = df.iloc[:, 2].values
JyJy = df.iloc[:, 3].values
JzJz = df.iloc[:, 4].values

# The sum of the autocorrelation functions for the three components
# The LAMMPS output is in (eV/ps/A^2)^2 * A^6 * ps = eV^2 / ps
HFACF_sum = JxJx + JyJy + JzJz

# Time vector
time_array = df.iloc[:, 1].values * PS_TO_S # Convert time (ps) to seconds (s)

# -------------------- 3. Integration and Kappa Calculation --------------------

# Convert the HFACF sum to SI units: (eV^2/ps) * (J/eV)^2 * (ps/s) = J^2/s
HFACF_SI = HFACF_sum * (EV_TO_J**2 / PS_TO_S)

# Integrate the HFACF over time (using Simpson's rule for numerical integration)
# We integrate the entire calculated range.
integral_value = simps(HFACF_SI, time_array)

# Calculate the thermal conductivity (kappa) in W/m-K
kappa = (GK_FACTOR * integral_value)

# -------------------- 4. Output Results --------------------

print("\n--- Green-Kubo Thermal Conductivity Calculation ---")
print(f"Simulation Temperature (T): {T:.2f} K")
print(f"Simulation Volume (V): {V:.2e} m^3")
print(f"Integration Range (Max Time): {time_array[-1]:.2e} s")
print(f"Integrated HFACF Value (SI): {integral_value:.2e} J^2/s")
print(f"Final Thermal Conductivity (kappa): {kappa:.4f} W/m-K")
print("---------------------------------------------------\n")

# A plot of the HFACF is essential for validation (optional plotting code)
try:
    import matplotlib.pyplot as plt
    plt.figure(figsize=(10, 6))
    plt.plot(time_array * 1e12, HFACF_sum, label=r'$\sum_{i=x,y,z} \langle J_i(t) J_i(0) \rangle$')
    plt.xlabel('Time (ps)')
    plt.ylabel(r'HFACF ($\mathrm{eV^2/ps}$)')
    plt.title('Heat Flux Autocorrelation Function (HFACF)')
    plt.grid(True, linestyle='--')
    plt.legend()
    plt.show()
except ImportError:
    print("Matplotlib not installed. Cannot display plot. Install with: pip install matplotlib")
